#!/bin/bash

logOpt="-log"
startOpt="start"
removeOpt="remove"
helpOpt="--help"

if [[ $1 = $startCmd ]]
then
  if [[ $2 = $logOpt ]]
  then
    node -r /home/.net-server/usr/bin/log.js /home/.net-server/usr/bin/net-server.js
  else
    node /home/.net-server/usr/bin/net-server.js
  fi
elif [[ $1 = $removeCmd ]]
then
  sudo rm -r /home/.net-server/
  sudo dpkg -r tcp-server-chat
elif [[ $1 = $helpCmd ]]
then
  echo
  cat /home/.net-server/usr/bin/help/help.txt
else
  echo "Usage: tcp-server [ OPTION ]"
  echo "Type 'tcp-server --help' for aditional info"
fi
