#!/bin/bash

startOpt="start"
removeOpt="remove"
updateOpt="update"
versionOpt="version"
showlogOpt="show-log"
clearlogOpt="clear-log"
helpOpt="--help"
vKey="-v"
lKey="-l"
pKey="-p"

version=$(dpkg -l tcp-server-chat | tail -1 | tr -s ' ' | cut -d' ' -f3)

if [[ $1 = $startOpt ]]

then
  if [[ $2 = $lKey ]]
  then
    if [[ $3 = $pKey ]]
    then
      if [[ -n $4 ]]
      then
        sudo node -r /home/.net-server/usr/bin/log.js /home/.net-server/usr/bin/net-server.js $4
      else
        echo "ERRNOPORT: port argument required"
      fi
    else
      sudo node -r /home/.net-server/usr/bin/log.js /home/.net-server/usr/bin/net-server.js
    fi
  else
    node /home/.net-server/usr/bin/net-server.js
  fi

elif [[ $1 = $updateOpt ]]
then
  sudo curl -s https://raw.githubusercontent.com/o-rumiantsev/tcp-server-install/master/install/update | bash

elif [[ $1 = $removeOpt ]]
then
  sudo rm -r /home/.net-server/
  sudo dpkg -r tcp-server-chat

elif [[ $1 = $helpOpt ]]
then
  echo
  cat /home/.net-server/usr/bin/help/help.txt

elif [[ $1 = $vKey || $1 = $versionOpt ]]
then
  echo "v$version"

elif [[ $1 = $showlogOpt ]]
then
  cat /home/.net-server/usr/bin/log/logs.txt

elif [[ $1 = $clearlogOpt ]]
then
  sudo echo > /home/.net-server/usr/bin/log/logs.txt

else
  echo "Usage: tcp-server [ OPTION ]"
  echo "Type 'tcp-server --help' for aditional info"
fi
