#!/bin/bash

DIR="/home/.tcp-server"
sudo git clone https://github.com/o-rumiantsev/tcp-server-install "$DIR"

cd $DIR

sudo mkdir /home/.net-server/
sudo mkdir /home/.net-server/usr/
sudo mkdir /home/.net-server/DEBIAN/
sudo mkdir /home/.net-server/usr/bin/
sudo mkdir /home/.net-server/usr/bin/help
sudo mkdir /home/.net-server/usr/bin/log

sudo chmod +x $DIR/install/res/tcp-server

sudo cp $DIR/install/res/control /home/.net-server/DEBIAN/
sudo cp $DIR/install/res/help.txt /home/.net-server/usr/bin/help/
sudo cp $DIR/install/res/net-server.js /home/.net-server/usr/bin/
sudo cp $DIR/install/res/tcp-server /home/.net-server/usr/bin/
sudo cp -r $DIR/install/res/log/ /home/.net-server/usr/bin/
sudo cp $DIR/install/res/log.js /home/.net-server/usr/bin/

sudo sed -i '/# enable bash completion in interactive shells/{N;N;N;N;N;N;N;s/\n#/\n/g}' /etc/bash.bashrc

sudo rm /usr/share/bash-completion/completions/tcp-server
sudo cp $DIR/install/res/completion/tcp-server /usr/share/bash-completion/completions/

sudo fakeroot dpkg-deb -b /home/.net-server
sudo dpkg -i /home/.net-server.deb
sudo rm /home/.net-server.deb
sudo rm -r /home/.tcp-server

echo
echo "Installed successfully"
echo "To start tcp server: tcp-server start"
echo "To uninstall: tcp-server remove"
echo "Type 'tcp-server --help' for aditional info"
