#!/bin/bash

DIR="/home/.tcp-server"
sudo git clone https://github.com/o-rumiantsev/tcp-server-install "$DIR"

cd $DIR

sudo mkdir /home/.net-server/
sudo mkdir /home/.net-server/usr/
sudo mkdir /home/.net-server/DEBIAN/
sudo mkdir /home/.net-server/usr/bin/

sudo chmod +x $DIR/install/res/tcp-server-start
sudo chmod +x $DIR/install/res/tcp-server-remove

sudo cp $DIR/install/res/control /home/.net-server/DEBIAN/
sudo cp $DIR/install/res/net-server.js /home/.net-server/usr/bin/
sudo cp $DIR/install/res/tcp-server-start /home/.net-server/usr/bin/
sudo cp $DIR/install/res/tcp-server-remove /home/.net-server/usr/bin

sudo fakeroot dpkg-deb -b /home/.net-server
sudo dpkg -i /home/.net-server.deb
sudo rm /home/.net-server.deb

echo "Installed successfully"
echo "To start tcp server: tcp-server-start"
echo "To uninstall: tcp-server-remove"
