#!/bin/bash

DIR="/home/.tcp-server"
sudo git clone https://github.com/o-rumiantsev/tcp-server-install "$DIR"

cd $DIR

sudo mkdir /home/.net-server/
sudo mkdir /home/.net-server/usr/
sudo mkdir /home/.net-server/DEBIAN/
sudo mkdir /home/.net-server/usr/bin/

sudo chmod +x res/tcp-server-start
sudo chmod +x res/tcp-server-remove

sudo cp res/control /home/.net-server/DEBIAN/
sudo cp res/net-server.js /home/.net-server/usr/bin/
sudo cp res/tcp-server-start /home/.net-server/usr/bin/
sudo cp res/tcp-server-remove /home/.net-server/usr/bin

cd /home

sudo fakeroot dpkg-deb -b .net-server
sudo dpkg -i .net-server.deb
sudo rm .net-server.deb
