#!/bin/bash

DIR="/home/.tcp-server"

sudo dpkg -r tcp-server-chat
sudo cp -r /home/.net-server/usr/bin/log/ /home/
sudo rm -r /home/.net-server/

sudo git clone https://github.com/o-rumiantsev/tcp-server-install "$DIR"

sudo mkdir /home/.net-server/
sudo mkdir /home/.net-server/usr/
sudo mkdir /home/.net-server/DEBIAN/
sudo mkdir /home/.net-server/usr/bin/
sudo mkdir /home/.net-server/usr/bin/help
sudo mkdir /home/.net-server/usr/bin/log

sudo chmod +x $DIR/install/res/tcp-server

sudo cp $DIR/install/res/control /home/.net-server/DEBIAN/
sudo cp $DIR/install/res/help.txt /home/.net-server/usr/bin/help/
sudo cp $DIR/install/res/net-server.js /home/.net-server/usr/bin/
sudo cp $DIR/install/res/tcp-server /home/.net-server/usr/bin/
sudo cp -r /home/log/ /home/.net-server/usr/bin/
sudo cp $DIR/install/res/log.js /home/.net-server/usr/bin/

sudo fakeroot dpkg-deb -b /home/.net-server
sudo dpkg -i /home/.net-server.deb
sudo rm /home/.net-server.deb
sudo rm -r /home/.tcp-server

version=$(dpkg -l tcp-server-chat | tail -1 | tr -s ' ' | cut -d' ' -f3)

echo
echo "Updated successfully"
echo "v$version"
